# default conf

# test
test:
  checkpoint: ./exp/lstm_dnn_cirm
  use_cuda: True

save:
  dir: ./output/simu_linear
  sample_rate: 16000

# nnet
nnet_conf:
  win_len: 320
  win_inc: 160
  fft_len: 512
  win_type: hanning
  num_bins: 257
  ipd_num: 4
  rnn_units: 512
  rnn_layers: 3
  bidirectional: False
  ipd_index: 0,4;1,5;2,6;3,7
  cos: True
  sin: False

# dataloader:
datareader:
  file_name: ./wav_list/tt/linear_20.lst
  sample_rate: 16000











